# Generated by Django 5.2.8 on 2025-11-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
